<CompareScreen>:
    id: compareScreen
    orientation: 'vertical'
    BoxLayout:
        orientation: 'vertical'
        ScrollView:
            size_hint: 1, 1
            MDBoxLayout:
                id: comparebox
                orientation: 'vertical'
                size_hint_y: None
                padding: dp(10)
                height: self.minimum_height


<ContentReviews>
    spacing: "12dp"
    size_hint_y: None
    height: "120dp"